{% set name = "fps-lab" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_lab-{{ version }}.tar.gz
  sha256: 929021cec6155926b4ed9238d66c82c384cb314fd1fe4a0fcaecf796789839cd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.10.0,<0.11.0
    - babel
    - json5
    - importlib_metadata >=4.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_lab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  summary: An FPS plugin for the JupyterLab/Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
