{% set name = "fps-lab" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_lab-{{ version }}.tar.gz
  sha256: 146f13a7aece4d8827f62f508a6344aefc7bbcf0ae497fb8c8a361e251906c90

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.12.0,<0.13.0
    - babel
    - json5
    - importlib-metadata >=4.4

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_lab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  summary: An FPS plugin for the JupyterLab/Notebook API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
