{% set name = "fps-lab" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_lab-{{ version }}.tar.gz
  sha256: fd61aeefc6476c6f6069dafb30aa0b8d9f7dd710ceb8957c2f4b278576f2b3fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - babel
    - json5

test:
  imports:
    - fps_lab

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  summary: An FPS plugin for the JupyterLab/RetroLab API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
