schema_version: 1

context:
  version: "0.10.3"

package:
  name: fps-lab
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-lab/fps_lab-${{ version }}.tar.gz
    sha256: aea5e607e8df556d1ec73fbaa379c60dbcefb4c95cb89582b432c959c7fb340f

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.1,<0.15.0
    - json5
    - babel

tests:
  - python:
      imports: fps_lab
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/lab
  summary: An FPS plugin for the JupyterLab/Notebook API

extra:
  recipe-maintainers:
    - davidbrochart
